import { ALL_PERMISSIONS, PERMISSIONS, SystemRole, type Permission } from '@crm/shared';

const CRM_READS: Permission[] = [
  PERMISSIONS.CONTACTS_READ,
  PERMISSIONS.COMPANIES_READ,
  PERMISSIONS.LEADS_READ,
  PERMISSIONS.DEALS_READ,
  PERMISSIONS.TASKS_READ,
  PERMISSIONS.COMMENTS_READ,
  PERMISSIONS.ATTACHMENTS_READ,
];

const AGENT: Permission[] = [
  ...CRM_READS,
  PERMISSIONS.CONTACTS_CREATE,
  PERMISSIONS.CONTACTS_UPDATE,
  PERMISSIONS.COMPANIES_CREATE,
  PERMISSIONS.COMPANIES_UPDATE,
  PERMISSIONS.LEADS_CREATE,
  PERMISSIONS.LEADS_UPDATE,
  PERMISSIONS.LEADS_CONVERT,
  PERMISSIONS.DEALS_CREATE,
  PERMISSIONS.DEALS_UPDATE,
  PERMISSIONS.TASKS_CREATE,
  PERMISSIONS.TASKS_UPDATE,
  PERMISSIONS.COMMENTS_CREATE,
  PERMISSIONS.ATTACHMENTS_CREATE,
];

const MANAGER: Permission[] = [
  ...AGENT,
  PERMISSIONS.CONTACTS_DELETE,
  PERMISSIONS.COMPANIES_DELETE,
  PERMISSIONS.LEADS_DELETE,
  PERMISSIONS.DEALS_DELETE,
  PERMISSIONS.TASKS_DELETE,
  PERMISSIONS.COMMENTS_DELETE,
  PERMISSIONS.ATTACHMENTS_DELETE,
  PERMISSIONS.PIPELINES_MANAGE,
  PERMISSIONS.AUDIT_READ,
  PERMISSIONS.DATA_EXPORT,
  PERMISSIONS.DATA_IMPORT,
];

/** Набор прав каждой системной роли. Владелец — все права; админ — все, кроме управления организацией. */
export const SYSTEM_ROLE_PERMISSIONS: Record<SystemRole, Permission[]> = {
  [SystemRole.Owner]: ALL_PERMISSIONS,
  [SystemRole.Admin]: ALL_PERMISSIONS.filter(
    (p) => p !== PERMISSIONS.ORGANIZATIONS_MANAGE,
  ),
  [SystemRole.Manager]: MANAGER,
  [SystemRole.Agent]: AGENT,
  [SystemRole.Viewer]: CRM_READS,
};

export const SYSTEM_ROLE_NAMES: Record<SystemRole, string> = {
  [SystemRole.Owner]: 'Владелец',
  [SystemRole.Admin]: 'Администратор',
  [SystemRole.Manager]: 'Менеджер',
  [SystemRole.Agent]: 'Сотрудник',
  [SystemRole.Viewer]: 'Наблюдатель',
};
